services:
  backend:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    working_dir: /workspace/backend
    command: python app.py
    ports:
      - "5001:5001"
    volumes:
      - .:/workspace
    container_name: drone_backend

  frontend:
    image: node:18
    working_dir: /workspace/frontend/mi-app
    command: npm run serve -- --host 0.0.0.0 --port 5173
    ports:
      - "5173:5173"
    volumes:
      - .:/workspace
    container_name: drone_frontend
